on:
  push:
    branches:
    - master
jobs:
  test:
    name: test code
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: setup virtual env
      uses: actions/setup-python@v6.0.0
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest
